### ISSUE TITLE
funcion CalculaMultas

### ISSUE THREAD

**Issue by jorgedemiguele** [aigora/twE105-polize_zass#4]
En la primera parte del programa faltaría hacer una función que calcule las multas, en esta debe buscar que radar ha impuesto la multa, que calcule la diferencia entre la velocidad limite de ese radar y la velocidad a la que iba el conductor, y dependiendo de la diferencia imponga la multa correspondiente

**Comment by Alberto1166** [comment]
Ya he completado la funcion CalculaMultas
